### ISSUE TITLE
supervisor.addons.validate

### ISSUE THREAD

**Issue by SPEC1AL1ST** [Draggon/hassio-hdd-tools#14]
Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of HDD Tools

**Comment by boesing** [comment]
Can you please verify if the error is gone with the latest release?
0.47 is available.

**Comment by SPEC1AL1ST** [comment]
> Can you please verify if the error is gone with the latest release?
> 0.47 is available.

It works, thank you! Message is gone.
