### ISSUE TITLE
jq: error (at <stdin>:1): object ({"unit_of_m...) and array ([{"id":5,"n...) cannot be added

### ISSUE THREAD

**Issue by SPEC1AL1ST** [Draggon/hassio-hdd-tools#15]
Error in logs

[Tue Mar  9 08:38:03 EET 2021][Info] HDD Tools start
[Tue Mar  9 08:38:03 EET 2021][Info] Configuration - performance check enabled: false
[Tue Mar  9 08:38:03 EET 2021][Info] Configuration - disk path: /dev/sda
[Tue Mar  9 08:38:03 EET 2021][Info] Configuration - check period: 1
[Tue Mar  9 08:38:03 EET 2021][Info] Configuration - output file: temp.log
[Tue Mar  9 08:38:03 EET 2021][Info] Configuration - attributes property: ata_smart_attributes.table
[Tue Mar  9 08:38:03 EET 2021][Info] Init run
jq: error (at <stdin>:1): object ({"unit_of_m...) and array ([{"id":5,"n...) cannot be added
[Tue Mar  9 08:38:05 EET 2021][INFO] Sensor value: 36°
[Tue Mar  9 08:38:05 EET 2021][INFO] Sensor update response code: 400
[Tue Mar  9 08:38:05 EET 2021][Info] Cron tab update
[Tue Mar  9 08:38:05 EET 2021][Info] Apply cron tab
[Tue Mar  9 08:38:05 EET 2021][Info] Device /dev/sda found - starting CRON
jq: error (at <stdin>:1): object ({"unit_of_m...) and array ([{"id":5,"n...) cannot be added
[Tue Mar  9 08:39:01 EET 2021][INFO] Sensor value: 37°
[Tue Mar  9 08:39:01 EET 2021][INFO] Sensor update response code: 400

Config:
https://c2n.me/4be0vCP

**Comment by boesing** [comment]
Please enable debug mode and provide the content of the file `output_file` you've configured.

When providing errors like this or file contents, please make use of the markdown Feature: 
https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code
