### ISSUE TITLE
Sensor update response code: 400

### ISSUE THREAD

**Issue by Ikif** [Draggon/hassio-hdd-tools#2]
I use USB3 case for HDD Seagate 500G connected to RPi4.
https://www.amazon.com/gp/product/B01LY97QE8/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1
I don't get temperature result.
[Thu Aug 13 16:30:55 IDT 2020][Info] Performance test end
[Thu Aug 13 16:30:55 IDT 2020][Info] Cron tab update
[Thu Aug 13 16:30:55 IDT 2020][Info] Apply cron tab
[Thu Aug 13 16:30:55 IDT 2020][Info] Device /dev/sda found - staring CRON
[Thu Aug 13 16:31:01 IDT 2020][Info] Sensor value: °
[Thu Aug 13 16:31:01 IDT 2020][Info] Sensor update response code: 400
[Thu Aug 13 16:32:01 IDT 2020][Info] Sensor value: °
[Thu Aug 13 16:32:01 IDT 2020][Info] Sensor update response code: 400
[Thu Aug 13 16:33:00 IDT 2020][Info] Sensor value: °
[Thu Aug 13 16:33:01 IDT 2020][Info] Sensor update response code: 400
[Thu Aug 13 16:34:01 IDT 2020][Info] Sensor value: °
[Thu Aug 13 16:34:01 IDT 2020][Info] Sensor update response code: 400
[Thu Aug 13 16:35:01 IDT 2020][Info] Sensor value: °
[Thu Aug 13 16:35:01 IDT 2020][Info] Sensor update response code: 400

**Comment by amorim1005** [comment]
same thing here

[Mon Sep 28 16:12:53 WEST 2020][Info] HDD Tools start
[Mon Sep 28 16:12:53 WEST 2020][Info] Configuration - disk path: /dev/sda
[Mon Sep 28 16:12:53 WEST 2020][Info] Configuration - check period: 1
[Mon Sep 28 16:12:53 WEST 2020][Info] Configuration - output file: temp.log
[Mon Sep 28 16:12:53 WEST 2020][Info] Init run
/share/hdd_tools/scripts/main.sh: line 11: -1: substring expression < 0
[Mon Sep 28 16:12:53 WEST 2020][Info] Sensor value: °
[Mon Sep 28 16:12:53 WEST 2020][Info] Sensor update response code: 400
[Mon Sep 28 16:12:53 WEST 2020][Info] Run performance test
     Category                  Test                      Result              
HDParm                    Disk Read                 277.88 MB/s              
HDParm                    Cached Disk Read          222.91 MB/s              
DD                        Disk Write                146 MB/s                 
FIO                       4k random read            22188 IOPS (88754 KB/s)  
FIO                       4k random write           3131 IOPS (12527 KB/s)   
IOZone                    4k read                   15599 KB/s               
IOZone                    4k write                  15221 KB/s               
IOZone                    4k random read            15250 KB/s               
IOZone                    4k random write           19122 KB/s               
                          Score: 5526                                        
Compare with previous benchmark results at:
https://storage.jamesachambers.com/ 
[Mon Sep 28 16:14:00 WEST 2020][Info] Performance test end
[Mon Sep 28 16:14:00 WEST 2020][Info] Cron tab update
[Mon Sep 28 16:14:00 WEST 2020][Info] Apply cron tab
[Mon Sep 28 16:14:00 WEST 2020][Info] Device /dev/sda found - staring CRON

**Comment by carsten-h** [comment]
Did you switched off "Protection mode" in the settings of HDD Tools?
After I did this, I am getting the values!

**Comment by amorim1005** [comment]
yes. and also the sensor.hdd_temp is not being created automatically

Carsten <notifications@github.com> escreveu no dia terça, 29/09/2020 à(s)
09:02:

**Comment by boesing** [comment]
I've created a PR which is already merged by @Draggon.
You might check the README as you can now configure the attribute you want to use to get the attributes from.
The temperature should be parsed properly even without changing the configuration.

**Comment by boesing** [comment]
Closing this for now as there has been no further feedback.
