### ISSUE TITLE
[supervisor.docker.addon] Add-on HDD Tools try to access to blocked device sda!

### ISSUE THREAD

**Issue by redneckdba** [Draggon/hassio-hdd-tools#36]
Most likely since upgrading HA to the latest and greatest version the hdd temperature sensor is missing and the following error message is logged in supervisor's log after restarting HA:
`
ERROR (SyncWorker_0) [supervisor.docker.addon] Add-on HDD Tools try to access to blocked device sda!
`
In addition the addon's log is filled with these messages:
`
jq: 1 compile error
[Thu Oct  7 19:38:01 CEST 2021][INFO] Sensor value: null°
[Thu Oct  7 19:38:01 CEST 2021][DEBUG] Sensor data which would be pushed to home-assistant and exposed as "sensor.hdd_temp": 
[Thu Oct  7 19:38:01 CEST 2021][DEBUG] debug is enabled, sensor data is not published to home-assistant!
jq: error: syntax error, unexpected '{', expecting $end (Unix shell quoting issues?) at <top-level>, line 2:
{}
`
System:
HA OS on RPi 4
Core: core-2021.10.0
supervisor:  supervisor-2021.09.6
HA OS 6.4

**Comment by McGiverGim** [comment]
This has been reported here https://github.com/Draggon/hassio-hdd-tools/issues/35

I close this, you can continue in the other issue.
