### ISSUE TITLE
After deinstallation of HDD Tools, I still get message in supervisor log 

### ISSUE THREAD

**Issue by habitoti** [Draggon/hassio-hdd-tools#42]
After I deinstalled the HDD Tools, the supervisor log still shows this entry (2 times) on HA startup: 

```
Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of HDD Tools
```

**Comment by McGiverGim** [comment]
You need to remove the repo too. It shows warnings for all the repos, not only installed ones.

**Comment by habitoti** [comment]
Thanks!
