### ISSUE TITLE
Failed to install addon

### ISSUE THREAD

**Issue by Vittaly76** [Draggon/hassio-hdd-tools#43]
I'm trying to install addon, but when i try to add this repo, i get error:

`Repostitory structure for v0.51.0 is not compliant`

HA ver 2021.11.3
HACS ver 1.17.0

**Comment by nepozs** [comment]
It is not intended for HACS (it is addon and not a custom component)
![addon_store](https://user-images.githubusercontent.com/56661567/142424295-5b565a9a-ac71-410e-aa37-fdac6f00d46e.png)
.

**Comment by Vittaly76** [comment]
It's clear, thank you!

**Comment by nepozs** [comment]
So if you have installed this addon with success, you should close issue.
