### ISSUE TITLE
WARNING (MainThread) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of HDD Tools

### ISSUE THREAD

**Issue by anglrus** [Draggon/hassio-hdd-tools#44]
Hello,
I have such warning:
WARNING (MainThread) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of HDD Tools

HDD Tools - Current version: 0.51.0
RPI 4 4Gb
HASSIO - core-2021.11.5
supervisor-2021.10.8

Thank you

**Comment by McGiverGim** [comment]
Yes, it was intended to see if the Home Assistant team changes back his code to not need to disable the protection mode. But it does not seem it will happen.
I will fix that in the next release.
