### ISSUE TITLE
How to get overall health state?

### ISSUE THREAD

**Issue by fokcuk** [Draggon/hassio-hdd-tools#45]
Want to get an overall health status, not the attributes:

  "smart_status": {
    "passed": true
  },

**Comment by McGiverGim** [comment]
I think it has sense. Maybe this must be principal value of the sensor, and all the other, including the temperature, be the attributes.
The biggest problem with this is is that it will be a breaking change probably.

**Comment by McGiverGim** [comment]
I've pushed a PR https://github.com/Draggon/hassio-hdd-tools/pull/46 that I think will fix this. Can you take a look at it?
