### ISSUE TITLE
Unable to install addon 

### ISSUE THREAD

**Issue by yousaf465** [Draggon/hassio-hdd-tools#52]
HA 2022.4.5 
Add-on version 0.52.0
Install stuck at revolving circle. 
![image](https://user-images.githubusercontent.com/83491212/164159445-d061cc2e-a6e5-4546-8013-96a828923d58.png)

**Comment by McGiverGim** [comment]
Look at the supervisor logs, maybe there is some error there. Without any error giving more information I think I can't help.

**Comment by yousaf465** [comment]
fixed, installed on fifth attempt. 
Now the issue is the frequency of temperature updates, is too low 
![image](https://user-images.githubusercontent.com/83491212/164220930-8d73a499-c2fc-4176-80ce-81bdc3a933b3.png)
![image](https://user-images.githubusercontent.com/83491212/164221000-29c22713-8b7b-40b6-a1c0-0b37dc0f6f11.png)

**Comment by McGiverGim** [comment]
Look at the logs of the addon, you will see when it updates. Is configurable in the addon.

**Comment by yousaf465** [comment]
same value since last 24hours no update from 52C. 
```
[Thu Apr 21 18:49:03 PKT 2022][INFO] Sensor update response code: 200
[Thu Apr 21 18:50:02 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 18:50:02 PKT 2022][INFO] Sensor update response code: 200
[Thu Apr 21 18:51:03 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 18:51:03 PKT 2022][INFO] Sensor update response code: 200
[Thu Apr 21 18:52:03 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 18:52:03 PKT 2022][INFO] Sensor update response code: 200
[Thu Apr 21 18:53:03 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 18:53:03 PKT 2022][INFO] Sensor update response code: 200
[Thu Apr 21 18:54:03 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 18:54:03 PKT 2022][INFO] Sensor update response code: 200
[Thu Apr 21 18:55:03 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 18:55:03 PKT 2022][INFO] Sensor update response code: 200
[Thu Apr 21 18:56:02 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 18:56:02 PKT 2022][INFO] Sensor update response code: 200
[Thu Apr 21 18:57:02 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 18:57:02 PKT 2022][INFO] Sensor update response code: 200
[Thu Apr 21 18:58:02 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 18:58:02 PKT 2022][INFO] Sensor update response code: 200
[Thu Apr 21 18:59:02 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 18:59:02 PKT 2022][INFO] Sensor update response code: 200
[Thu Apr 21 19:00:02 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 19:00:02 PKT 2022][INFO] Sensor update response code: 200
[Thu Apr 21 19:01:02 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 19:01:02 PKT 2022][INFO] Sensor update response code: 200
[Thu Apr 21 19:02:02 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 19:02:02 PKT 2022][INFO] Sensor update response code: 200
[Thu Apr 21 19:03:02 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 19:03:02 PKT 2022][INFO] Sensor update response code: 200
[Thu Apr 21 19:04:02 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 19:04:02 PKT 2022][INFO] Sensor update response code: 200
[Thu Apr 21 19:05:02 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 19:05:02 PKT 2022][INFO] Sensor update response code: 200
[Thu Apr 21 19:06:02 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 19:06:02 PKT 2022][INFO] Sensor update response code: 200
[Thu Apr 21 19:07:02 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 19:07:02 PKT 2022][INFO] Sensor update response code: 200
[Thu Apr 21 19:08:03 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 19:08:03 PKT 2022][INFO] Sensor update response code: 200
[Thu Apr 21 19:09:02 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 19:09:02 PKT 2022][INFO] Sensor update response code: 200
```

![image](https://user-images.githubusercontent.com/83491212/164476747-ad0d10a5-f9f6-4b1d-a4da-ec6956adb071.png)

```
sensor_state_type: temperature
sensor_name: sensor.hdd_smart
friendly_name: Hdd SMART
hdd_path: /dev/sda
attributes_format: object
attributes_property: ''
check_period: 1
database_update: true
database_update_period: 168
performance_check: false
debug: false
output_file: temp.log

```

**Comment by McGiverGim** [comment]
It seems to be working. Strange the temperature without change. Enable the debug and paste here the file generated, maybe there is something there.
What I see is that you are not configuring the attributes property, maybe if it is wrong, it happens something like this.

**Comment by yousaf465** [comment]
> It seems to be working. Strange the temperature without change. Enable the debug and paste here the file generated, maybe there is something there. What I see is that you are not configuring the attributes property, maybe if it is wrong, it happens something like this.

how to enable debug? 
which attributes should be changed? 

what should choose here?
![image](https://user-images.githubusercontent.com/83491212/164478868-24c53290-1f0e-4878-a8c0-a0409c994762.png)

**Comment by yousaf465** [comment]
enabled  debug got this 

```
[Thu Apr 21 20:05:02 PKT 2022][DEBUG] Sensor data before attributes: {"state": "52", "attributes": {"unit_of_measurement":"°C","friendly_name":"Hdd SMART","device_class":"temperature","state_class":"measurement"}}
[Thu Apr 21 20:05:02 PKT 2022][DEBUG] Sensor data which would be pushed to home-assistant and exposed as "sensor.hdd_smart": {"state": "52", "attributes": {"unit_of_measurement":"°C","friendly_name":"Hdd SMART","device_class":"temperature","state_class":"measurement"}}
[Thu Apr 21 20:05:02 PKT 2022][DEBUG] debug is enabled, sensor data is not published to home-assistant!
[Thu Apr 21 20:06:02 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 20:06:02 PKT 2022][DEBUG] Sensor data before attributes: {"state": "52", "attributes": {"unit_of_measurement":"°C","friendly_name":"Hdd SMART","device_class":"temperature","state_class":"measurement"}}
[Thu Apr 21 20:06:02 PKT 2022][DEBUG] Sensor data which would be pushed to home-assistant and exposed as "sensor.hdd_smart": {"state": "52", "attributes": {"unit_of_measurement":"°C","friendly_name":"Hdd SMART","device_class":"temperature","state_class":"measurement"}}
[Thu Apr 21 20:06:02 PKT 2022][DEBUG] debug is enabled, sensor data is not published to home-assistant!
[Thu Apr 21 20:07:02 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 20:07:02 PKT 2022][DEBUG] Sensor data before attributes: {"state": "52", "attributes": {"unit_of_measurement":"°C","friendly_name":"Hdd SMART","device_class":"temperature","state_class":"measurement"}}
[Thu Apr 21 20:07:02 PKT 2022][DEBUG] Sensor data which would be pushed to home-assistant and exposed as "sensor.hdd_smart": {"state": "52", "attributes": {"unit_of_measurement":"°C","friendly_name":"Hdd SMART","device_class":"temperature","state_class":"measurement"}}
[Thu Apr 21 20:07:02 PKT 2022][DEBUG] debug is enabled, sensor data is not published to home-assistant!
[Thu Apr 21 20:08:02 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 20:08:02 PKT 2022][DEBUG] Sensor data before attributes: {"state": "52", "attributes": {"unit_of_measurement":"°C","friendly_name":"Hdd SMART","device_class":"temperature","state_class":"measurement"}}
[Thu Apr 21 20:08:02 PKT 2022][DEBUG] Sensor data which would be pushed to home-assistant and exposed as "sensor.hdd_smart": {"state": "52", "attributes": {"unit_of_measurement":"°C","friendly_name":"Hdd SMART","device_class":"temperature","state_class":"measurement"}}
[Thu Apr 21 20:08:02 PKT 2022][DEBUG] debug is enabled, sensor data is not published to home-assistant!
[Thu Apr 21 20:09:02 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 20:09:02 PKT 2022][DEBUG] Sensor data before attributes: {"state": "52", "attributes": {"unit_of_measurement":"°C","friendly_name":"Hdd SMART","device_class":"temperature","state_class":"measurement"}}
[Thu Apr 21 20:09:02 PKT 2022][DEBUG] Sensor data which would be pushed to home-assistant and exposed as "sensor.hdd_smart": {"state": "52", "attributes": {"unit_of_measurement":"°C","friendly_name":"Hdd SMART","device_class":"temperature","state_class":"measurement"}}
[Thu Apr 21 20:09:02 PKT 2022][DEBUG] debug is enabled, sensor data is not published to home-assistant!
[Thu Apr 21 20:10:02 PKT 2022][INFO] Sensor value as temperature: 52
[Thu Apr 21 20:10:02 PKT 2022][DEBUG] Sensor data before attributes: {"state": "52", "attributes": {"unit_of_measurement":"°C","friendly_name":"Hdd SMART","device_class":"temperature","state_class":"measurement"}}
[Thu Apr 21 20:10:02 PKT 2022][DEBUG] Sensor data which would be pushed to home-assistant and exposed as "sensor.hdd_smart": {"state": "52", "attributes": {"unit_of_measurement":"°C","friendly_name":"Hdd SMART","device_class":"temperature","state_class":"measurement"}}
[Thu Apr 21 20:10:02 PKT 2022][DEBUG] debug is enabled, sensor data is not published to home-assistant!
```

**Comment by McGiverGim** [comment]
I think it will generate a file in the shared folder of homessistant, could you try to find it?

**Comment by yousaf465** [comment]
> I think it will generate a file in the shared folder of homessistant, could you try to find it?

how do I access it? I can access \\192.168.1.8\config folder through windows

**Comment by yousaf465** [comment]
found 
[hdddebug.log](https://github.com/Draggon/hassio-hdd-tools/files/8532379/hdddebug.log)

  \\192.168.1.8\share\hdd_tools

**Comment by McGiverGim** [comment]
> what should choose here?

The one that references your disk, not a partition (the only one that does not have `partX` at the end).

In the debug file I can see two things:
1. The temperature detected by the smartmoontools in the ADATA SU750 is 52ºC:
```
      {
        "id": 194,
        "name": "Temperature_Celsius",
        "value": 100,
        "worst": 100,
        "thresh": 0,
        "when_failed": "",
        "flags": {
          "value": 50,
          "string": "-O--CK ",
          "prefailure": false,
          "updated_online": true,
          "performance": false,
          "error_rate": false,
          "event_count": true,
          "auto_keep": true
        },
        "raw": {
          "value": 52,
          "string": "52"
        }
      },
```
and
```
  "temperature": {
    "current": 52
  },

```
2. In the configuration, the correct `attributes` value must be `list` and the `attributes_property` must be `ata_smart_attributes.table`

**Comment by yousaf465** [comment]
> > what should choose here?
> 
> The one that references your disk, not a partition (the only one that does not have `partX` at the end).
> 
> In the debug file I can see two things:
> 
> 1. The temperature detected by the smartmoontools in the ADATA SU750 is 52ºC:
> 
> ```
>       {
>         "id": 194,
>         "name": "Temperature_Celsius",
>         "value": 100,
>         "worst": 100,
>         "thresh": 0,
>         "when_failed": "",
>         "flags": {
>           "value": 50,
>           "string": "-O--CK ",
>           "prefailure": false,
>           "updated_online": true,
>           "performance": false,
>           "error_rate": false,
>           "event_count": true,
>           "auto_keep": true
>         },
>         "raw": {
>           "value": 52,
>           "string": "52"
>         }
>       },
> ```
> 
> and
> 
> ```
>   "temperature": {
>     "current": 52
>   },
> ```
> 
> 2. In the configuration, the correct `attributes` value must be `list` and the `attributes_property` must be `ata_smart_attributes.table`

Is it 'ata_smart_attributes.table' as attribute property? NO SATA_SMART...?

**Comment by McGiverGim** [comment]
> Is it 'ata_smart_attributes.table' as attribute property? NO SATA_SMART...?

Yes, this is from your debug file:
```
  },
  "ata_smart_attributes": {
    "revision": 10,
    "table": [
      {
        "id": 1,
```

It has nothing to do with the connection, is the JSON returned by the smartmontools.

**Comment by yousaf465** [comment]
> > Is it 'ata_smart_attributes.table' as attribute property? NO SATA_SMART...?
> 
> Yes, this is from your debug file:
> 
> ```
>   },
>   "ata_smart_attributes": {
>     "revision": 10,
>     "table": [
>       {
>         "id": 1,
> ```
> 
> It has nothing to do with the connection, is the JSON returned by the smartmontools.

this is how the configuration looks like right now. Is it fine? 

![image](https://user-images.githubusercontent.com/83491212/164617086-8f6e4a29-3a43-4ebf-b6a5-7e2723b4e6e5.png)

![image](https://user-images.githubusercontent.com/83491212/164617110-7eb81268-a24e-4f0e-a1b6-b63748a8339d.png)

**Comment by McGiverGim** [comment]
Yes. Disable the debug.

**Comment by nepozs** [comment]
@yousaf465 
If temperature never change, you should use variant with binary smart_state sensor.
Some models of ssd report false temperature (they are without hardware sensor), it is easy to find - it just never change.

**Comment by yousaf465** [comment]
> @yousaf465 If temperature never change, you should use variant with binary smart_state sensor. Some models of ssd report false temperature (they are without hardware sensor), it is easy to find - it just never change.

How do I do that?

**Comment by nepozs** [comment]
Example:
![hdd_tools_smart_2022-04-26_14-59](https://user-images.githubusercontent.com/56661567/165305523-c8d0b333-1d01-4012-808d-797b4e7f8ac3.png)

It is common situation with cheap ssd hardware (some manufactures use generic firmware, but they do not mount sensors, so firmware report always the same value) e.g. PNY CS900, some Adata models, many Natec models, mine SanDisk U110  (it is dedicated to ThinClients so every cent is important, but only SanDisk firmware does not show false sensor temperature).


BTW 
I will never buy Adata or Natec products again due to warranty issues. In the case of Adata, I will also avoid the XPG brand, Natec SSDs are sold under many (mainly Chinese) brands, so it is important not to buy unfamiliar brands.

**Comment by McGiverGim** [comment]
@yousaf465 Usually is good read and not simply ask: https://github.com/Draggon/hassio-hdd-tools/blob/develop/hdd_tools/DOCS.md
