### ISSUE TITLE
s6-overlay-suexec: fatal: can only run as pid 1

### ISSUE THREAD

**Issue by Koterak** [Draggon/hassio-hdd-tools#53]
When starting addon there is `s6-overlay-suexec: fatal: can only run as pid 1` error.

Possibly because of this: https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/

**Comment by McGiverGim** [comment]
I don't understand exactly the problem or the solution... Let's see if someone clever than me can help...

**Comment by nepozs** [comment]
Problem looks like: after update HA core to >=2022.6.0 current addon version (0.52.0) can't start due error:
`s6-overlay-suexec: fatal: can only run as pid 1`
![HDD_Tools_s6-overlay-suexec_fatal_can_only_run_as_pid_1_2022-06-22_15-40](https://user-images.githubusercontent.com/56661567/175043823-c5d36dfe-5157-46bf-bdf6-a0b68a99514a.png)
(so last version where addon can work without changes is 2022.5.5)
it's a pity that HDD Tools can't be used anymore (without changes in addon).

@Koterak 
As alternative you can use Scrutiny addon if you add to the Shop repository
`https://github.com/alexbelgium/hassio-addons`

@McGiverGim 
Maybe @alexbelgium can help you (as addons from his repository contain updated s6init)
https://github.com/alexbelgium/hassio-addons

**Comment by alexbelgium** [comment]
Hi, here are the changes to make : https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/

At least "init: false" in config.json and making all scripts executable. Hopefully it is enough, or else you'll have to check the whole guide ;) good luck

**Comment by McGiverGim** [comment]
Thanks! I will do the change and push it, to see if it is enough...

**Comment by McGiverGim** [comment]
It works!! Thanks!!

@Koterak @nepozs can you test the new version that I've published right now? It seems to be working, at least for me...

**Comment by nepozs** [comment]
Yes, it works, I've tested on 2 different installations.
